// kernel.c
#define DISPLAY_THEME GREEN_ON_BLACK
#define KERNEL_STARTUP ksh_start();

// mem.h
#define KERNEL_MEMORY_OFFSET_START 0x10000
#define KERNEL_MEMORY_OFFSET_END	0xffffffff
#define MEMORY_INDEX_BASE_SIZE 10000
