name: Make build CI

on:
  push:
    branches:
      [ main ]
  pull_request:
    branches:
      [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: make
        run: apt install -y make gcc nasm; make
